---
format_version: "10"
pipelines:
  hello_app:
    group: java-spring-apps
    materials:
      mygit:
        git: http://example.com/mygit.git
        branch: main
    stages:
      - build-app:
          jobs:
            build-app:
              tasks:
                - exec:
                    command: echo
                    arguments:
                      - "Building hello-app"
